export const ROOM_TYPE_OPTIONS = [
  'Alfresco',
  'Alfresco #1',
  'Alfresco #2',
  'Alfresco #3',
  'Alfresco #4',
  'Bedroom - Guest',
  'Bedroom #1',
  'Bedroom #2',
  'Bedroom #3',
  'Bedroom #4',
  'Bedroom #5',
  'Breakfast Area',
  "Butler's Pantry",
  'Carport',
  'Cellar',
  'Courtyard',
  'Dining Room',
  'Ensuite',
  'Ensuite #1',
  'Ensuite #2',
  'Ensuite #3',
  'Ensuite #4',
  'Ensuite #5',
  'Entry',
  'Family Room',
  'Formal Living Room',
  'Formal Lounge',
  'Front Door',
  'Games Room',
  'Garage',
  'Gym',
  'Hallway',
  'Hallway #1',
  'Hallway #2',
  'Hallway #3',
  'Kitchen',
  'Landing',
  'Laundry',
  'Library',
  'Living Room',
  'Living Room #1',
  'Living Room #2',
  'Lounge Room',
  'Lounge Room #1',
  'Lounge Room #2',
  'Master',
  'Master Retreat',
  'Meals Area',
  'Media Room',
  'Mudroom',
  'Music Room',
  'Nursery',
  'Office',
  'Pantry',
  'Patio',
  'Pool Room',
  'Porch',
  'Powder Room',
  'Rumpus Room',
  'Sitting Room',
  'Stairwell',
  'Storage Room',
  'Study',
  'Sunroom',
  'TV Room',
  'Utility Room',
  'Verandah',
  'Verandah #1',
  'Verandah #2',
  'Verandah #3',
  'Verandah #4',
  'Walk In Pantry',
  'Walk In Robe',
  'WC',
  'WC #1',
  'WC #2',
  'WIR',
  'Workshop',
  'Study Nook',
]

/**
 * Normalizes a location for comparison only (trims whitespace, lower-cases, collapses
 * internal spacing). Never use this for display -- the user-facing label must be preserved
 * verbatim so "Bedroom 1" and "Bedroom 2" stay distinct rooms.
 */
export function normalizeLocationKey(location: string): string {
  return location.trim().toLowerCase().replace(/\s+/g, ' ')
}
