import { expect, test } from '@playwright/test'
import { addOpening, resetApp } from './helpers'

test.beforeEach(async ({ page }) => {
  await resetApp(page)
  await page.goto('/quotes/new')
  await page.getByLabel('Customer', { exact: true }).fill('Customer with two addresses')
  await page.getByLabel('Email addresses', { exact: true }).fill('customer@example.com,accounts@example.com')
  await page.getByLabel('Site address', { exact: true }).fill('1 Site Street')
})

test('same-address checkbox keeps billing in sync through creation and edits', async ({ page }) => {
  const same = page.getByLabel('Billing address is the same as site address')
  await expect(same).toBeChecked()
  await expect(page.getByLabel('Billing address', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('Billing address', { exact: true })).toHaveValue('1 Site Street')
  await page.getByRole('button', { name: 'Start quote', exact: true }).click()
  await expect(page.getByLabel('Email addresses', { exact: true })).toHaveValue('customer@example.com,accounts@example.com')
  await page.getByLabel('Site address', { exact: true }).fill('2 Updated Site Street')
  await expect(page.getByLabel('Billing address', { exact: true })).toHaveValue('2 Updated Site Street')
  await same.uncheck()
  await page.getByLabel('Billing address', { exact: true }).fill('3 Accounts Street')
  await expect(page.getByLabel('Site address', { exact: true })).toHaveValue('2 Updated Site Street')
  await same.check()
  await expect(page.getByLabel('Billing address', { exact: true })).toHaveValue('2 Updated Site Street')
  await page.getByRole('button', { name: 'Save quote', exact: true }).click()
  await page.reload()
  await expect(same).toBeChecked()
  await expect(page.getByLabel('Site address', { exact: true })).toHaveValue('2 Updated Site Street')
  await expect(page.getByLabel('Billing address', { exact: true })).toHaveValue('2 Updated Site Street')
})

test('separate addresses and multiple emails survive saving and appear in the customer preview', async ({ page }) => {
  await page.getByLabel('Billing address is the same as site address').uncheck()
  await page.getByLabel('Billing address', { exact: true }).fill('9 Billing Road')
  await page.getByRole('button', { name: 'Start quote', exact: true }).click()
  await expect(page.getByLabel('Site address', { exact: true })).toHaveValue('1 Site Street')
  await expect(page.getByLabel('Billing address', { exact: true })).toHaveValue('9 Billing Road')
  await addOpening(page)
  await page.getByRole('button', { name: 'Save quote', exact: true }).click()
  await page.reload()
  await expect(page.getByLabel('Billing address is the same as site address')).not.toBeChecked()
  await expect(page.getByLabel('Site address', { exact: true })).toHaveValue('1 Site Street')
  await expect(page.getByLabel('Billing address', { exact: true })).toHaveValue('9 Billing Road')
  await expect(page.getByLabel('Email addresses', { exact: true })).toHaveValue('customer@example.com,accounts@example.com')
  await page.getByRole('button', { name: 'Preview Customer Quote', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Preview quote' })
  const bill = dialog.locator('.quote-party').filter({ hasText: 'Billing address:' })
  const site = dialog.locator('.quote-party').filter({ hasText: 'Site address:' })
  await expect(bill).toContainText('9 Billing Road')
  await expect(bill).toContainText('customer@example.com,accounts@example.com')
  await expect(site).toContainText('1 Site Street')
})
