import { expect, test } from '@playwright/test'
import { fillRoomLocation, resetApp, startNewQuote } from './helpers'

test.beforeEach(async ({ page }) => {
  await resetApp(page)
  await startNewQuote(page)
})

test('selects configuration then product before measuring and hides flyscreen triple locks', async ({ page }) => {
  await page.getByRole('link', { name: '+ Add Opening' }).click()
  await fillRoomLocation(page, 'Bedroom 1')
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Pick a configuration' })).toBeVisible()
  await page.getByRole('button', { name: /^HDX-L\b/ }).click()
  await expect(page.getByRole('heading', { name: 'Select a product' })).toBeVisible()
  await page.getByRole('button', { name: 'Fly Screens', exact: true }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Measure the opening' })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: /Centre tongue/ })).toHaveCount(0)
  await page.getByLabel('H1', { exact: true }).fill('2100')
  await page.getByLabel('W1', { exact: true }).fill('900')
  await expect(page.getByLabel('H2', { exact: true })).toHaveValue('2100')
  await expect(page.getByLabel('W3', { exact: true })).toHaveValue('900')
  await page.getByRole('checkbox', { name: 'Mid-rail required' }).check()
  await expect(page.getByRole('button', { name: 'Continue' })).toBeDisabled()
  await page.getByLabel('Mid-rail height (mm)').fill('1050')
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Add-ons' })).toBeVisible()
  await expect(page.getByRole('row', { name: /TRIPLE LOCKS/ })).toHaveCount(0)
})

test('records three lock positions, mid-rail and sliding interlock with an editable add-on price', async ({ page }) => {
  await page.getByRole('link', { name: '+ Add Opening' }).click()
  await fillRoomLocation(page, 'Patio')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: /^SDOX\b/ }).click()
  await page.getByRole('button', { name: '7mm Diamond', exact: true }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('H1', { exact: true }).fill('2100')
  await page.getByLabel('W1', { exact: true }).fill('900')
  await page.getByRole('checkbox', { name: /Centre tongue/ }).check()
  await expect(page.getByLabel('Lock height (mm)')).toHaveValue('N/A')
  await page.getByLabel('Top lock position (mm)').fill('1833')
  await page.getByLabel('Centre lock position (mm)').fill('1250')
  await page.getByLabel('Bottom lock position (mm)').fill('257')
  await page.getByRole('checkbox', { name: 'Mid-rail required' }).check()
  await page.getByLabel('Mid-rail height (mm)').fill('1000')
  await page.getByRole('checkbox', { name: /Door interlock needed/ }).check()
  await expect(page.getByText(/Opening used for sizing: 2100 × 900 mm/)).toBeVisible()
  await expect(page.getByText(/Size used for pricing: 2100 × 455 mm/)).toBeVisible()
  await page.getByRole('button', { name: 'Continue' }).click()
  const tripleLocks = page.getByRole('row', { name: /TRIPLE LOCKS/ })
  await tripleLocks.getByRole('checkbox').check()
  await tripleLocks.getByRole('spinbutton', { name: 'TRIPLE LOCKS price' }).fill('125')
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByText(/Top 1833 · Centre 1250 · Bottom 257 mm/)).toBeVisible()
  await expect(page.getByText('5 mm added')).toBeVisible()
  await page.getByRole('button', { name: 'Save Item' }).click()
  await expect(page.locator('.quote-item-card')).toContainText('Patio')
  await expect(page.locator('.quote-item-card')).toContainText('2100 × 900 mm')
})

test('adds a repair without choosing a product from the Current Quote button', async ({ page }) => {
  const addOpening = page.getByRole('link', { name: '+ Add Opening' })
  const addRepair = page.getByRole('link', { name: '+ Add Extra / Repair' })
  await expect(addRepair).toBeVisible()
  await expect(addRepair).toHaveClass(/quote-workspace__add/)
  await expect(addOpening).toHaveClass(/quote-workspace__add/)
  await addRepair.click()
  await fillRoomLocation(page, 'Bedroom 1')
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Add-ons' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Product', exact: true })).toHaveCount(0)
  await page.getByLabel('Extra / repair description').fill('Re-mesh existing flyscreen window')
  await page.getByLabel('Work price ($)').fill('80')
  const callOut = page.getByRole('row', { name: /CALL OUT FEE/ })
  await callOut.getByRole('checkbox').check()
  await callOut.getByRole('spinbutton', { name: 'CALL OUT FEE price' }).fill('95')
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByText('Extra / repair only')).toBeVisible()
  await page.getByRole('button', { name: 'Save Item' }).click()
  await expect(page.locator('.quote-item-card')).toContainText('Re-mesh existing flyscreen window')
})
